import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    page: {
        flex: 1,
        paddingHorizontal: 24,
        justifyContent: "center",
        backgroundColor: "#f5f7fb",
        overflow: "hidden",
    },
    bgBlobA: {
        position: "absolute",
        width: 210,
        height: 210,
        borderRadius: 999,
        backgroundColor: "rgba(15,98,254,0.10)",
        top: -55,
        left: -55,
    },
    bgBlobB: {
        position: "absolute",
        width: 240,
        height: 240,
        borderRadius: 999,
        backgroundColor: "rgba(66,133,244,0.12)",
        bottom: -70,
        right: -70,
    },
    heroWrap: {
        marginBottom: 18,
        alignItems: "center",
    },
    logo: {
        width: 92,
        height: 92,
        marginBottom: 14,
        borderRadius: 24,
    },
    brandTitle: {
        color: "#17324d",
        fontSize: 34,
        lineHeight: 40,
        fontWeight: "900",
        marginBottom: 8,
        textAlign: "center",
    },
    formCard: {
        backgroundColor: "rgba(255,255,255,0.92)",
        borderWidth: 1,
        borderColor: "#dbe6f5",
        borderRadius: 18,
        padding: 18,
        shadowColor: "#0d1c2f",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.08,
        shadowRadius: 18,
        elevation: 3,
    },
    subtitle: {
        marginTop: 8,
        color: "#0f62fe",
        fontSize: 16,
        fontWeight: "700",
        lineHeight: 22,
        textAlign: "center",
    },
    input: {
        borderWidth: 1,
        borderColor: "#d4dde7",
        borderRadius: 10,
        backgroundColor: "#fff",
        color: "#1a3047",
        paddingHorizontal: 14,
        paddingVertical: 12,
        marginBottom: 12,
    },
    inputError: {
        borderColor: "#bd1e1e",
    },
    fieldError: {
        color: "#bd1e1e",
        fontSize: 13,
        marginTop: -7,
        marginBottom: 10,
    },
    primaryButton: {
        backgroundColor: "#0f62fe",
        borderRadius: 10,
        paddingVertical: 14,
        alignItems: "center",
        marginTop: 4,
    },
    primaryButtonText: {
        color: "#fff",
        fontWeight: "700",
    },
    link: {
        marginTop: 18,
        textAlign: "center",
        color: "#0f62fe",
        fontWeight: "600",
        lineHeight: 20,
    },
    error: {
        color: "#bd1e1e",
        marginBottom: 8,
    },
});

export default styles;
